# Generated by Django 4.0.3 on 2022-03-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_items_category_items_cat_id_alter_items_fbx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_register',
            name='fullname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
