# Generated by Django 4.0.3 on 2022-03-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_admin_register_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_register',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
